Combine ZStackEdit and TrackEdit classes to ensure consistent `cell_info` contents
vanvalenlab/deepcell-label pull request #281
Opened 2021-11-29 22:59 UTC by tddough98

Since we've added tracking to the current build of DeepCell Label, we've been creating tracking metadata for all projects so that any project could use the tracking code and UI. However, the edit route still distinguished between tracking and zstack projects using the extension of the file used to create the project. Only files ending with .trk or .trks are edited with TrackEdit, and all other files are edited with ZStackEdit. As each class implements its own `add_cell_info` and `del_cell_info`, editing with the ZStackEdit would not maintain the tracking metadata as expected.

Issue #280 revealed this issue, as a project with no initial labels would have an empty `cell_info` dict, and once we start adding labels using the ZStackEdit class, the `cell_info` would not have the expected fields. The route that serves `cell_info` expects these fields to be present, and serves an error instead and causing NaN to be appear the selected label.

Here the TrackEdit and ZStackEdit classes are unified into a single Edit class so that all projects are both initialized and updated with the same consistent set of field in its `cell_info` dict. I also removed actions that are not currently used.

2021-11-30 22:16 UTC, willgraf requested changes
Looks awesome, a great improvement. In addition to a couple of small questions, it looks like there is some `etag` test failure going on.

2021-11-30 22:16 UTC, willgraf commented on visualizer/src/service/apiMachine.js
> +    const header = response.headers['content-disposition'];
Why the switch from `fetch` to `axios`?

2021-11-30 22:16 UTC, willgraf commented on deepcell_label/utils.py
> +    return snake_pattern.sub(lambda x: x.group(1).upper(), name)
Might as well throw in a test for this too.

2021-12-03 23:07 UTC, tddough98 commented on visualizer/src/service/apiMachine.js
> +    const header = response.headers['content-disposition'];
Switched back to fetch

2021-12-03 23:50 UTC, willgraf approved these changes
💯

2021-12-03 23:53 UTC, merged