Add deployment guide
vanvalenlab/deepcell-label pull request #335
Opened 2022-06-17 20:05 UTC by tddough98

This adds a markdown file to walk through creating and configuring the cloud resources to put DeepCell Label online. As I'll be leaving next month, it's intended to serve as a resource for future work on the project to make sure it can be redeployed and updated. As we discover new required configuration and switch the resources we use, we should update this guide with the up to date steps for deployment.

2022-06-17 23:43 UTC, msschwartz21 requested changes
Looks great! Everything went pretty well with my run through. I left suggestions in places that I thought needed additional clarification.

2022-06-17 23:43 UTC, msschwartz21 commented on DEPLOYMENT.md
> +
```suggestion

Before deploying the instance, confirm that you have set the following values in the `.env` file:
- `AWS_ACCESS_KEY_ID`
- `AWS_SECRET_ACCESS_KEY`
- `S3_BUCKET` - this is the bucket where you will store files uploaded to DCL 
- `SQLALCHEMY_DATABASE_URI`

```

2022-06-22 20:20 UTC, tddough98 commented on DEPLOYMENT.md
> +mysql --host=deepcell-label-db-1.cbwvcgkyjfot.us-east-2.rds.amazonaws.com --user=deepcelladmin --password -P 3306
This information is not sensitive, but it's not a bad idea to take it offline. It reveals the endpoint for the database and the username, but not the password. I will put the complete command in the admin slack channel and put placeholders here instead

2022-06-23 20:29 UTC, msschwartz21 approved these changes

2022-06-23 20:37 UTC, merged

2025-01-28 21:31 UTC, WeihaoGe1009 commented
To who this may concern,

I was trying to follow the deployment guide on an AWS EC2 instance and failed at a very early stage. 
besides installing prerequisits for mysql-client, node.js, npm, and yarn, now i'm at the very first step following https://github.com/vanvalenlab/deepcell-label/blob/main/documentation/DEPLOYMENT.md, section "Host a static site with an S3 bucket". I have created a bucket and updated the policy, and then try to build the front end with yarn. Then, I was kept with the error message:

../angle/src/libANGLE/HandleAllocator.cpp: In constructor ‘gl::HandleAllocator::HandleAllocator()’:
../angle/src/libANGLE/HandleAllocator.cpp:29:52: error: ‘numeric_limits’ is not a member of ‘std’
   29 |     mUnallocatedList.push_back(HandleRange(1, std::numeric_limits<GLuint>::max()));
      |                                                    ^~~~~~~~~~~~~~
../angle/src/libANGLE/HandleAllocator.cpp:29:76: error: ‘::max’ has not been declared; did you mean ‘std::max’?
   29 |     mUnallocatedList.push_back(HandleRange(1, std::numeric_limits<GLuint>::max()));
      |                                                                            ^~~
      |                                                                            std::max
In file included from /usr/include/c++/11/algorithm:62,
                 from ../angle/src/libANGLE/HandleAllocator.cpp:12:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
../angle/src/libANGLE/HandleAllocator.cpp:29:43: error: expected primary-expression before ‘(’ token
   29 |     mUnallocatedList.push_back(HandleRange(1, std::numeric_limits<GLuint>::max()));
      |                                           ^
../angle/src/libANGLE/HandleAllocator.cpp:29:52: error: ‘numeric_limits’ is not a member of ‘std’
   29 |     mUnallocatedList.push_back(HandleRange(1, std::numeric_limits<GLuint>::max()));
      |                                                    ^~~~~~~~~~~~~~
../angle/src/libANGLE/HandleAllocator.cpp:29:73: error: expected primary-expression before ‘>’ token
   29 |     mUnallocatedList.push_back(HandleRange(1, std::numeric_limits<GLuint>::max()));
      |                                                                         ^
../angle/src/libANGLE/HandleAllocator.cpp:29:76: error: ‘::max’ has not been declared; did you mean ‘std::max’?
   29 |     mUnallocatedList.push_back(HandleRange(1, std::numeric_limits<GLuint>::max()));
      |                                                                            ^~~
      |                                                                            std::max
In file included from /usr/include/c++/11/algorithm:62,
                 from ../angle/src/libANGLE/HandleAllocator.cpp:12:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
make: *** [angle/src/libANGLE.target.mk:241: Release/obj.target/libANGLE/angle/src/libANGLE/HandleAllocator.o] Error 1
make: Leaving directory '/home/ec2-user/deepcell-label/frontend/node_modules/gl/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ec2-user/deepcell-label/frontend/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
gyp ERR! System Linux 6.1.119-129.201.amzn2023.x86_64
gyp ERR! command "/home/ec2-user/.nvm/versions/node/v18.20.5/bin/node" "/home/ec2-user/deepcell-label/frontend/node_modules/gl/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/ec2-user/deepcell-label/frontend/node_modules/gl

I tried different ways to patch the file HandleAllocator.cpp with '#include <limits>' but it always got reset during the installation. Sometimes I was able to fix it after node-gyp rebuild, but never able to get through the yarn command, i.e. the very first command on the page. Could you help me to deploy DeepCell Label on AWS please?