Fix bugs related to cells not properly deleting
vanvalenlab/deepcell-label pull request #368
Opened 2022-08-23 00:42 UTC by ykevu

## What
Addressed the bug from Issue #365, in which after deleting a cell, one cannot write over the deleted cell's area when using exclusion mode. 

Additionally, added some snippets of code required for the tests and source code to run on Windows.

## Fix
The bug arose because the deleted cell was only removed from the cells matrix but its label persisted in the labels matrix. Added a new function to the Edit class called clean_labels() which deletes any labels that do not correspond to existing cells that is called every time an action is performed that adds masks (eg. brush, flood, etc.). Additionally, a more esoteric bug was found involving overlapped cells reappearing after deletion, which should be addressed by this change as well.

## Why
Users can now properly edit areas previously occupied by deleted cells, rendering the delete tool usable in exclusion mode.

2022-08-23 02:24 UTC, tddough98 commented
The repeated `delete_temp` declarations can be factored out into `config.py` and imported from there. Also instead of `my_variable = True if condition else False`, use `my_variable = condition`.

In config.py,
```
DELETE_TEMP = platform.system() != 'Windows'
```
and then in each module that defines delete_temp locally, import `DELETE_TEMP` and replace `delete_temp` with `DELETE_TEMP`.

2022-08-23 02:30 UTC, tddough98 commented on backend/deepcell_label/label.py
> +        labeled[deleted_mask] = 0  # delete any labels not in values
`np.isin` would preserve the shape of labeled so you don't have to reshape after. Both `isin` and `in1d` have an invert parameter that can bypass the `logical_not`.

```
deleted_mask = np.isin(labeled, values, invert=True)
labeled[deleted_mask] = 0
```

2022-08-24 19:41 UTC, msschwartz21 requested changes
Please address the other changes that Tom suggested and fix the linting error that is causing a test to fail. Then I would be happy to approve!

2022-08-24 19:41 UTC, msschwartz21 commented on backend/deepcell_label/loaders_test.py
> +    delete_temp = False if platform.system() == 'Windows' else True
Import from config?

2022-08-24 19:41 UTC, msschwartz21 commented on backend/deepcell_label/loaders_test.py
> +    delete_temp = False if platform.system() == 'Windows' else True
Import from config?

2022-08-27 02:14 UTC, msschwartz21 approved these changes

2022-08-27 02:16 UTC, merged